### ISSUE TITLE
non issue: vscode-jest-snippets uninstalled by settings sync

### ISSUE THREAD

**Issue by dhensen** [andys8/vscode-jest-snippets#14]
I installed this, tried out some triggers.. nothing happens. I also added the `"editor.snippetSuggestions": "top"`

I looked at the snippet file your project defined, I see a `scope: "source.js"` Can you explain to me what this does? I have searched in vscode docs but can not find what this is supposed to do.

Then I installed another snippet extension (jundat95/react-native-snippet), that one worked out of the box (installed alongside your extension). This is also the reason I dont think it is necesarry for me to post my config, I also **don't** have custom files.associations. What do you think?

**Comment by andys8** [comment]
Hi @dhensen.

As stated in the credits part of the `README`, this extension was forked from `vscode-jasmine`. Scope was part of [its snippets](https://github.com/xabikos/vscode-jasmine/blob/master/snippets/snippets.json#L6). Threre is a [small part of the documentation](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_global-snippets), that refers to scopes with language identifiers. The [language identifier](https://code.visualstudio.com/docs/languages/identifiers) looks different, but `scope.js` could be a scope name.

Regarding your issue, there are two questions:
1. Is the `scope` field necessary and works?
2. Is `scope` or something else causing the extension not to work for you?

I will look into the `scope` field. It could limit the files the extension can be used. There is also the [`package.json` limiting the scope to ts and js](https://github.com/andys8/vscode-jest-snippets/blob/master/package.json#L24-L42). What is the file you tried the extension with? What extension did the file have? And what is the language mode in vscode (right bottom corner)?
I'm asking this, because it will not work in a "Plain Text" file, for example.

**Comment by dhensen** [comment]
Hi @andys8,

Thanks for the quick reply. I am using this on `*.test.js` and I have also tried it on `*.js`. I can confirm for both extensions it says JavaScript in the right bottom corner. (I have seen the package.json, but that should be ok because my files really are marked as being javascript)

I have not tried removing the scope field, I expect extensions to work out of the box (ofcourse after applying some kind of config). I will try coping it to my own snippet file and see what happens.

In the documentation link you provided, if I click through to `language identifier` I see an example where the groovy language has a ` "scopeName": "source.groovy",` inside the grammar key, I will check if I can find a source.js scope somewhere and report back.

I really want to use this extension. It amazes me that none of the other 11K users have this issue.

**Comment by dhensen** [comment]
The scope `source.js` is defined here:
https://github.com/Microsoft/vscode/blob/master/extensions/javascript/syntaxes/JavaScript.tmLanguage.json#L9

**Comment by dhensen** [comment]
Oh.... so stupid. Maybe this helps somebody else:

I use the Settings Sync plugin. Upon installing vscode-jest-snippets I had to reload. The settings sync plugin reloaded a config that did not yet include vscode-jest-snippets effectively uninstalling it. I now installed it again and it works fine!

Thanks for your time and sorry for confusion caused!

**Comment by andys8** [comment]
Glad to hear, you figured this out.

Thanks for your research in the `scope`. I'm not exactly sure about it's purpose, but I will leave it as it is for now, because it didn't do any harm.
