### ISSUE TITLE
2 snippet suggestions

### ISSUE THREAD

**Issue by GoGoris** [andys8/vscode-jest-snippets#15]
I like your plugin, I would like to share the snippets I added locally in my own setup:

jfn -> jest.fn()
shouldrender ->
    "it('should render', () => {",
    "\texpect(fixture).toMatchSnapshot();",
    "});"

**Comment by GoGoris** [comment]
Maybe the second one is too specific, but I really like the first one because I write a lot of mocks. I think that it could be a nice addition to the plugin.

**Comment by andys8** [comment]
Thanks for your input!

### jest.fn()

Threre are a [bunch of functions](https://facebook.github.io/jest/docs/en/jest-object.html) on the `jest` object. I did not not plan to integrate them, because they can be accessed with intellisense/autocompletion. But I think `jest.fn()` is perhaps used frequently enough to be integrated in the snippets.

### it should match snapshot

There is a snippet for `it` and for `to match snapshot`. But you want to propose a combination of those two, right?

**Comment by GoGoris** [comment]
Thanks for your quick response! I did not know that the `to match snapshot` snippet did almost the same thing. Using `it` and `tms` is more flexible so I can live without the shouldrender snippet now 👍 
A jest.fn() snippet would be nice though.
