### ISSUE TITLE
Remap names

### ISSUE THREAD

**Issue by tomitrescak** [andys8/vscode-jest-snippets#19]
Hi, thanks for the amazing snippets.
My issue is that I hate having snippets first so the solution for putting snippets on top is no good.
This renders most snippets, or the most used snippets unusable.

Would you know if I could remap your snippets to new prefixes?
For example "te" to "jte" ?

**Comment by andys8** [comment]
Hi, thanks for the kind words. Snippets allow not a lot of customization. It would be possible to have the snippets duplicated with other prefixes, but I wouldn't do that because of duplication.

Users can create custom snippets in vscode. You could grab the `snippets.json` from the repository, paste them in your custom javascript snippet file and modify all the prefixes. 

https://code.visualstudio.com/docs/editor/userdefinedsnippets
