### ISSUE TITLE
Option to use double quotes instead of single

### ISSUE THREAD

**Issue by WickyNilliams** [andys8/vscode-jest-snippets#2]
It would be handy if i could configure the use of single or double quotes for snippets

**Comment by andys8** [comment]
Hi @WickyNilliams, thanks for the input. As far as I know vs code [snippet extensions](https://code.visualstudio.com/docs/editor/userdefinedsnippets) can't be configured. Not sure about that. I chose the single quote option because It's used in [jest docs](https://facebook.github.io/jest/docs/en/api.html) and more popular.

What you can do, is reuse the [provided snippets](https://github.com/andys8/vscode-jest-snippets/blob/master/snippets/snippets.json), modify them with double quotes and add them to your custom snippets (`File -> Preferences -> User Snippets`)
