### ISSUE TITLE
Option to remove semicolons

### ISSUE THREAD

**Issue by dan-kez** [andys8/vscode-jest-snippets#8]
Hello!

My eslint rules enforce no semicolons. At present I just run a '--fix' action on every save which handles this but it would be preferable if we could chose not to add semi-colons in the first place.

**Comment by andys8** [comment]
I mentioned it in another issue before: I'm not aware of a way to provide configuration for snippet extensions in vs code. This would be the way to go. Because otherwise everybody who wanted to have semicolons got them removed. As long as there is no configuration the snippets have to be opinionated. 

https://code.visualstudio.com/docs/editor/userdefinedsnippets

There is a way to fix it locally: Copy the snippets content in your local snippets file and modify the body.
